local fa = io.open("a.txt","a")
local fa = io.open("a.txt","r")
--print(fa:read())
local fa1 = fa:read("*a")
fb = io.open("b.txt","r")
local fb1 = fb:read("*a")
print(fa1 .. fb1)
fb:close()
local f3 = io.open("c.txt","w")
--f3:write(fa1 .. fb1)
f3:close()
fb = io.open("b.txt","w")
fb:write(fa1 .. fb1)
